apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: edu-user-hpa
  namespace: edu-user
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edu-user-deployment  # Deployment 이름 참조
  minReplicas: 2  # 최소 Pod 수
  maxReplicas: 4  # 최대 Pod 수
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30