apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edu-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/NavyHubb/k8s-manifest.git'
    targetRevision: HEAD
    path: /projects/project-edu
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - path: edu-user  # edu-user Application
    - path: edu-goods # edu-goods Application